Describe 'ai-mem compact retrieval APIs' {
    BeforeAll {
        $repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
        $script:functionApiPath = Join-Path $repoRoot 'api\memory_api\run.py'
        $script:functionApiText = Get-Content $functionApiPath -Raw
        $script:embeddingWorkerPath = Join-Path $repoRoot 'api\embedding_worker\run.py'
        $script:embeddingWorkerText = Get-Content $embeddingWorkerPath -Raw
        $script:mcpBridgePath = Join-Path $repoRoot 'scripts\mcp\ai_mem_server.py'
        $script:mcpBridgeText = Get-Content $mcpBridgePath -Raw
        $script:portableClientPyprojectPath = Join-Path $repoRoot 'client\pyproject.toml'
        $script:portableClientPyprojectText = Get-Content $portableClientPyprojectPath -Raw
        $script:portableClientMcpPath = Join-Path $repoRoot 'client\src\ai_mem\mcp_server.py'
        $script:portableClientMcpText = Get-Content $portableClientMcpPath -Raw
        $script:portableClientCliPath = Join-Path $repoRoot 'client\src\ai_mem\cli.py'
        $script:portableClientCliText = Get-Content $portableClientCliPath -Raw
        $script:portableClientCorePath = Join-Path $repoRoot 'client\src\ai_mem\client.py'
        $script:portableClientCoreText = Get-Content $portableClientCorePath -Raw
        $script:buildScriptPath = Join-Path $repoRoot 'scripts\azure\Invoke-CodexMemoryAzureBuild.ps1'
        $script:buildScriptText = Get-Content $buildScriptPath -Raw
        $script:clientSetupPath = Join-Path $repoRoot 'scripts\azure\Invoke-CodexMemoryClientSetup.ps1'
        $script:clientSetupText = Get-Content $clientSetupPath -Raw
        $script:clientPackageBuildScriptPath = Join-Path $repoRoot 'scripts\azure\Build-CodexMemoryAzureClientPackage.ps1'
        $script:clientPackageBuildScriptText = Get-Content $clientPackageBuildScriptPath -Raw
    }

    It 'exposes additive compact retrieval operations in the Function API' {
        $functionApiText | Should -Match 'def memory_search_summaries'
        $functionApiText | Should -Match 'def memory_get_items'
        $functionApiText | Should -Match 'def memory_get_stats'
        $functionApiText | Should -Match 'def project_upsert'
        $functionApiText | Should -Match 'def project_get'
        $functionApiText | Should -Match 'def project_list'
        $functionApiText | Should -Match 'def project_archive'
        $functionApiText | Should -Match 'def memory_route_review'
        $functionApiText | Should -Match 'def memory_add_disagreement'
        $functionApiText | Should -Match 'def memory_build_context'
        $functionApiText | Should -Match 'def memory_get_retrieval_logs'
        $functionApiText | Should -Match 'def memory_get_audit_events'
        $functionApiText | Should -Match 'def memory_export'
        $functionApiText | Should -Match 'def memory_import'
        $functionApiText | Should -Match 'def memory_rebuild_embeddings'
        $functionApiText | Should -Match 'def memory_auto_promote'
        $functionApiText | Should -Match 'def keyword_overlap'
        $functionApiText | Should -Match 'canonicalHash'
        $functionApiText | Should -Match 'visibility'
        $functionApiText | Should -Match 'importance'
        $functionApiText | Should -Match 'confidence'
        $functionApiText | Should -Match 'projectId'
        $functionApiText | Should -Match 'memoryScope'
        $functionApiText | Should -Match 'memoryClass'
        $functionApiText | Should -Match 'trustScore'
        $functionApiText | Should -Match 'trustDimensions'
        $functionApiText | Should -Match 'promotionStatus'
        $functionApiText | Should -Match 'derivedFromIds'
        $functionApiText | Should -Match 'artifactRef'
        $functionApiText | Should -Match 'default_memory_class'
        $functionApiText | Should -Match 'build_trust_dimensions'
        $functionApiText | Should -Match 'infer_retrieval_intent'
        $functionApiText | Should -Match 'preferred_memory_class'
        $functionApiText | Should -Match 'scope_multiplier'
        $functionApiText | Should -Match 'trust_multiplier'
        $functionApiText | Should -Match 'rankingSignals'
        $functionApiText | Should -Match 'channelFit'
        $functionApiText | Should -Match 'temporalFit'
        $functionApiText | Should -Match 'referenceCount'
        $functionApiText | Should -Match 'lastReferenced'
        $functionApiText | Should -Match '_compute_dynamic_trust_dimensions'
        $functionApiText | Should -Match '_record_retrieval_feedback'
        $functionApiText | Should -Match '_evaluate_promotion'
        $functionApiText | Should -Match '_ensure_project_exists'
        $functionApiText | Should -Match 'route_review_policy'
        $functionApiText | Should -Match 'projectFilter'
        $functionApiText | Should -Match 'embeddingMode'
        $functionApiText | Should -Match 'degraded_hash'
        $functionApiText | Should -Match 'retrieval_log'
        $functionApiText | Should -Match 'detect_conflicts'
        $functionApiText | Should -Match '_validate_signed_context'
        $functionApiText | Should -Match '_queue_embedding_job'
        $functionApiText | Should -Match 'TextBase64EncodePolicy'
        $functionApiText | Should -Match '_extract_run_candidates'
        $functionApiText | Should -Match '"transient_memory"'
        $functionApiText | Should -Match '"memory_search_summaries": service\.memory_search_summaries'
        $functionApiText | Should -Match '"memory_get_items": service\.memory_get_items'
        $functionApiText | Should -Match '"memory_get_stats": service\.memory_get_stats'
        $functionApiText | Should -Match '"project_upsert": service\.project_upsert'
        $functionApiText | Should -Match '"project_get": service\.project_get'
        $functionApiText | Should -Match '"project_list": service\.project_list'
        $functionApiText | Should -Match '"project_archive": service\.project_archive'
        $functionApiText | Should -Match '"memory_route_review": service\.memory_route_review'
        $functionApiText | Should -Match '"memory_add_disagreement": service\.memory_add_disagreement'
        $functionApiText | Should -Match '"memory_build_context": service\.memory_build_context'
        $functionApiText | Should -Match '"memory_get_retrieval_logs": service\.memory_get_retrieval_logs'
        $functionApiText | Should -Match '"memory_get_audit_events": service\.memory_get_audit_events'
        $functionApiText | Should -Match '"memory_export": service\.memory_export'
        $functionApiText | Should -Match '"memory_import": service\.memory_import'
        $functionApiText | Should -Match '"memory_rebuild_embeddings": service\.memory_rebuild_embeddings'
        $functionApiText | Should -Match '"memory_auto_promote": service\.memory_auto_promote'
        $functionApiText | Should -Match 'budget must be one of: small, medium, full'
    }

    It 'validates retrieval ranking multipliers and no-answer gate logic' {
        $functionApiText | Should -Match 'NOISE_TOKENS'
        $functionApiText | Should -Match 'RECENCY_QUERY_TERMS'
        $functionApiText | Should -Match 'CHANNEL_SPECIFIC_TERMS'
        $functionApiText | Should -Match 'def temporal_query_multiplier'
        $functionApiText | Should -Match 'def channel_specificity_multiplier'
        $functionApiText | Should -Match 'def should_return_summary_matches'
        $functionApiText | Should -Match 'def keyword_tokens'
        $functionApiText | Should -Match 'def _extract_latest_date'
        $functionApiText | Should -Match 'channel_specificity_multiplier\(query_text, item\)'
        $functionApiText | Should -Match 'temporal_query_multiplier\(query_text, item\)'
        $functionApiText | Should -Match 'gate_allowed = bool\(gate_eval\.get\("allow"\)\)'
        $functionApiText | Should -Match 'SUMMARY_GATE_MIN_SCORE'
        $functionApiText | Should -Match 'SUMMARY_GATE_MIN_VECTOR'
        $functionApiText | Should -Match 'SUMMARY_GATE_MIN_LEXICAL'
        $functionApiText | Should -Match 'def evaluate_summary_gate'
    }

    It 'ships a portable repo-independent client package with MCP and CLI entrypoints' {
        $portableClientPyprojectText | Should -Match 'name = "ai-mem"'
        $portableClientPyprojectText | Should -Match 'ai-mem = "ai_mem\.cli:main"'
        $portableClientPyprojectText | Should -Match 'ai-mem-mcp = "ai_mem\.mcp_server:main"'
        $portableClientCoreText | Should -Match 'class ClientConfig'
        $portableClientCoreText | Should -Match 'def post_operation'
        $portableClientCoreText | Should -Match 'def install_codex_mcp_server'
        $portableClientCoreText | Should -Match 'x-codex-context-signature'
        $portableClientMcpText | Should -Match 'def memory_search_summaries'
        $portableClientMcpText | Should -Match 'def memory_get_items'
        $portableClientMcpText | Should -Match 'def memory_get_stats'
        $portableClientMcpText | Should -Match 'def memory_project_upsert'
        $portableClientMcpText | Should -Match 'def memory_project_get'
        $portableClientMcpText | Should -Match 'def memory_project_list'
        $portableClientMcpText | Should -Match 'def memory_project_archive'
        $portableClientMcpText | Should -Match 'def memory_route_review'
        $portableClientMcpText | Should -Match 'def memory_add_disagreement'
        $portableClientMcpText | Should -Match 'def memory_build_context'
        $portableClientMcpText | Should -Match 'def memory_get_retrieval_logs'
        $portableClientMcpText | Should -Match 'def memory_get_audit_events'
        $portableClientMcpText | Should -Match 'def memory_export'
        $portableClientMcpText | Should -Match 'def memory_import'
        $portableClientMcpText | Should -Match 'def memory_rebuild_embeddings'
        $portableClientMcpText | Should -Match 'def memory_auto_promote'
        $portableClientMcpText | Should -Match 'project_id: str = ""'
        $portableClientMcpText | Should -Match 'preferred_memory_class: str = ""'
        $portableClientMcpText | Should -Match 'memory_class: str = "semantic"'
        $portableClientMcpText | Should -Match 'trust_dimensions_json: str = ""'
        $portableClientCliText | Should -Match 'prog="ai-mem"'
        $portableClientCliText | Should -Match 'add_parser\("add-run"\)'
        $portableClientCliText | Should -Match 'add_parser\("add-fact"\)'
        $portableClientCliText | Should -Match 'add_parser\("search"\)'
        $portableClientCliText | Should -Match 'add_parser\("stats"\)'
        $portableClientCliText | Should -Match 'add_parser\("retrieval-logs"\)'
        $portableClientCliText | Should -Match 'add_parser\("audit-logs"\)'
        $portableClientCliText | Should -Match 'add_parser\("rebuild-embeddings"\)'
        $portableClientCliText | Should -Match 'add_parser\("promote"\)'
        $portableClientCliText | Should -Match 'add_parser\("project-upsert"\)'
        $portableClientCliText | Should -Match 'add_parser\("project-get"\)'
        $portableClientCliText | Should -Match 'add_parser\("project-list"\)'
        $portableClientCliText | Should -Match 'add_parser\("project-archive"\)'
        $portableClientCliText | Should -Match 'add_parser\("route-review"\)'
        $portableClientCliText | Should -Match 'add_parser\("add-disagreement"\)'
        $portableClientCliText | Should -Match 'add_parser\("orchestrate-review"\)'
        $portableClientCliText | Should -Match 'add_parser\("install-mcp"\)'
        $portableClientCliText | Should -Match '--preferred-memory-class'
        $portableClientCliText | Should -Match '--project-id'
        $portableClientCoreText | Should -Not -Match 'Path\.cwd\(\)\.name'
        $mcpBridgeText | Should -Match 'from ai_mem\.mcp_server import main'
    }

    It 'validates the new retrieval endpoints during ai-mem Azure build' {
        $buildScriptText | Should -Match 'memory_search_summaries'
        $buildScriptText | Should -Match 'memory_build_context'
        $buildScriptText | Should -Match 'summaryCount'
        $buildScriptText | Should -Match 'contextItemCount'
        $buildScriptText | Should -Match 'retrieval_log'
        $buildScriptText | Should -Match 'embedding-jobs'
        $buildScriptText | Should -Match 'MEMORY_HMAC_SECRET'
        $buildScriptText | Should -Match 'x-codex-context-signature'
        $buildScriptText | Should -Match '--shared-secret'
        $buildScriptText | Should -Match 'pip", "install", "--user", "--upgrade"'
        $buildScriptText | Should -Match 'ai_mem\.cli'
        $buildScriptText | Should -Match 'install-mcp'
        $buildScriptText | Should -Match 'memory_build_context'
    }

    It 'ships a queue-triggered embedding worker' {
        $embeddingWorkerText | Should -Match 'embedding_job_completed'
        $embeddingWorkerText | Should -Match 'embedding_job_failed'
        $embeddingWorkerText | Should -Match 'embeddingStatus'
    }

    It 'updates client setup to configure signed MCP requests' {
        $clientSetupText | Should -Match 'MEMORY_HMAC_SECRET'
        $clientSetupText | Should -Match '--shared-secret'
        $clientSetupText | Should -Match 'pip", "install", "--user", "--upgrade"'
        $clientSetupText | Should -Match 'ai_mem\.mcp_server'
        $clientSetupText | Should -Match 'install-mcp'
        $buildScriptText | Should -Match 'EMBEDDING_WRITE_MODE=queue'
    }

    It 'includes a package build helper for portable release artifacts' {
        $clientPackageBuildScriptText | Should -Match 'Invoke-Python -PythonArgs @\("-m", "build"'
        $clientPackageBuildScriptText | Should -Match 'ai-mem'
        $clientPackageBuildScriptText | Should -Match 'dist'
    }

    It 'enforces semantic embedding gates in deterministic deploy flow' {
        $deployScriptPath = Join-Path $repoRoot 'scripts\azure\Invoke-CodexMemoryFunctionDeploy.ps1'
        $deployScriptText = Get-Content $deployScriptPath -Raw
        $deployScriptText | Should -Match 'AllowDegradedEmbedding'
        $deployScriptText | Should -Match 'Assert-RequiredEmbeddingSettings'
        $deployScriptText | Should -Match 'AZURE_OPENAI_ENDPOINT'
        $deployScriptText | Should -Match 'AZURE_OPENAI_API_KEY'
        $deployScriptText | Should -Match 'AZURE_OPENAI_EMBED_DEPLOYMENT'
        $deployScriptText | Should -Match 'memory_search_vectors'
        $deployScriptText | Should -Match 'embeddingMode'
    }
}
